### ISSUE TITLE
Santize input

### ISSUE THREAD

**Issue by command7** [AjayRK2000/JPGtoPNG-converter#1]
https://github.com/AjayRK2000/JPGtoPNG-converter/blob/2d73d61b3c92c293b6ae47f1e8e144465b39d6a0/JPG_to_PNG.py#L5-L7

What if the user input is empty? Can we sanitize it?

```
if len(from_file) < 1 or len(to_file):
  # Error out saying user has provided empty input
```

**Comment by AjayRK2000** [comment]
> https://github.com/AjayRK2000/JPGtoPNG-converter/blob/2d73d61b3c92c293b6ae47f1e8e144465b39d6a0/JPG_to_PNG.py#L5-L7
> 
> What if the user input is empty? Can we sanitize it?
> 
> ```
> if len(from_file) < 1 or len(to_file):
>   # Error out saying user has provided empty input
> ```

Is None == False?

**Comment by command7** [comment]
Don't quite understand your question. Do you mean if None is equivalent to false inherently? If so no. None itself is a separate element and True or false depends on the condition check you do

```
x = None
if x == None:
  # Returns True

if x != None"
  # Returns False
```

**Comment by AjayRK2000** [comment]
You have len(to_file) as one of the conditions in the if-statement. 

Operating under the assumption that the user didn't enter "sys.argv[2]" in the Terminal, will len(to_file) evaluate to None or will it evaluate to False?

**Comment by command7** [comment]
That was a typo on my part. It was supposed to be 

```
if len(from_file) < 1 or len(to_file) < 1:
```

Now that you bring that up, there could be two situations where user does not provide the input.

1) User provides empty item as argument. For example: `python JPG_to_PNG.py "" ""`

In this case, our sanitization would take care of it

2) User could provide no argument. For example: `python JPG_to_PNG.py`

In this case, what would happen?


Based on the documentation, `argv` is a list and you would accessing an index that does not exist
```
sys.argv
The list of command line arguments passed to a Python script. argv[0] is the script name (it is operating system dependent whether this is a full pathname or not). If the command was executed using the [-c](https://docs.python.org/3/using/cmdline.html#cmdoption-c) command line option to the interpreter, argv[0] is set to the string '-c'. If no script name was passed to the Python interpreter, argv[0] is the empty string.

To loop over the standard input, or the list of files given on the command line, see the [fileinput](https://docs.python.org/3/library/fileinput.html#module-fileinput) module.
```

You would get `IndexError: list index out of range`. You can test it with a simple program

```
Vj-MacBook-Pro:~ vj$ cat temp.py
import sys

from_file = sys.argv[1]
to_file = sys.argv[2]

print(from_file)
print(to_file)
```

```
Vj-MacBook-Pro:~ vj$ python3 temp.py 1 2
1
2
```

```
Vj-MacBook-Pro:~ vj$ python3 temp.py
Traceback (most recent call last):
  File "temp.py", line 3, in <module>
    from_file = sys.argv[1]
IndexError: list index out of range
```


The program we write should not fail an unexpected areas. Can we sanitize this as follows
```
# We expect two arguments
# The value at index 0 is the script name
if len(sys.argv) < 3:
  # Error out that enough arguments were not provided
```

**Comment by AjayRK2000** [comment]
Aw man I would've liked to figure out that last part myself. It's alright. I'll get going on the commit

**Comment by command7** [comment]
Youll eventually get there :) 

Don't get intimidated by the documentation. Part of the job is just googling for the errors.

For example, I searched for `sys.argv index out of bounds` and found this https://stackoverflow.com/a/15122019

**Comment by AjayRK2000** [comment]
Oh I know all that. 

I was just saying I could've gotten there by myself and that I didn't need to be told the answer. That's all. I appreciate all the guidance though.

**Comment by command7** [comment]
Ah gotcha. Will stop with the questions from now onwards

**Comment by AjayRK2000** [comment]
see last 3 commits
