### ISSUE TITLE
Check if input is directory

### ISSUE THREAD

**Issue by command7** [AjayRK2000/JPGtoPNG-converter#2]
https://github.com/AjayRK2000/JPGtoPNG-converter/blob/2d73d61b3c92c293b6ae47f1e8e144465b39d6a0/JPG_to_PNG.py#L9-L11

What if the input the user gives is a file instead of directory?

```
if not os.path.isdir(from_file):
  # Error out or process just one file based on what the program's features are
```

**Comment by AjayRK2000** [comment]
check commit with message "ensure 1st argument is a directory"
