### ISSUE TITLE
Better variable naming

### ISSUE THREAD

**Issue by command7** [AjayRK2000/JPGtoPNG-converter#3]
https://github.com/AjayRK2000/JPGtoPNG-converter/blob/2d73d61b3c92c293b6ae47f1e8e144465b39d6a0/JPG_to_PNG.py#L6-L7

If the program expects the input to be folder names, can we name them as `source_folder` and `destination_folder` instead?

**Comment by AjayRK2000** [comment]
see commit with message "improve variable names"
